# ======================
# DeadCycle v0.6.2
# ======================

phase:
  day_seconds: 600
  night_seconds: 300

# ======================
# ECONOMY
# ======================
economy:
  start_money: 0
  kill_zombie_reward: 5

# ======================
# DIFFICULTY
# ======================
difficulty:
  zombie_hp_base: 16.0
  zombie_hp_per_day: 1.2
  zombie_dmg_base: 2.0
  zombie_dmg_per_day: 0.2

# ======================
# ZOMBIES
# ======================
zombies:
  enabled: true
  base_per_player: 2
  per_night_add: 1

  base_spawn_ring:
    min_outside: 10
    max_outside: 28

  spawn_radius_min: 12
  spawn_radius_max: 28
  spawn_y_offset: 2

# ======================
# BASE
# ======================
base:
  enabled: false
  world: world
  x: 0
  y: 64
  z: 0
  radius: 30
  spawn_y_offset: 1

# ======================
# BASE RESOURCES
# ======================
base_resources:
  money_per_point: 0.5
  points: 0
  by_type:
    stone: 0
    coal: 0
    iron: 0
    diamond: 0

# ======================
# BASE UPGRADES
# ======================
base_upgrades:
  radius:
    max: 60
    price_per_level: 500
  regen_speed:
    max: 5
    price_per_level: 350
  wall_hp:
    max: 5
    price_per_level: 400

# ======================
# SHOP
# ======================
shop:
  sell:
    COBBLESTONE: 1
    COAL: 4
    IRON_INGOT: 10
    GOLD_INGOT: 18
    DIAMOND: 60

  buy:
    # оружие / броня
    IRON_SWORD: 120
    IRON_CHESTPLATE: 250
    IRON_LEGGINGS: 220
    IRON_HELMET: 160
    IRON_BOOTS: 140
    SHIELD: 80
    BOW: 150

    # еда
    BREAD: 6
    COOKED_CHICKEN: 10
    COOKED_BEEF: 14
    GOLDEN_APPLE: 250

    # стрелы
    ARROW: 2
    ARROW_16: 40
    ARROW_64: 150

    # наборы еды
    FOOD_16_BREAD: 80
    FOOD_16_BEEF: 180

    # зелья
    POTION_HEALING: 180
    POTION_SWIFTNESS: 160
    POTION_STRENGTH: 220
    POTION_REGEN: 260

# ======================
# SIEGE (ОСАДА)
# ======================
siege:
  enabled: true
  only_at_night: true
  start_day: 3
  extra_radius: 8
  tick_interval: 10

  block_damage_base: 2
  block_damage_per_day: 0.3

  break_no_drops: true
  whitelist_only: true

# HP блоков (осада)
blocks_hp:
  OAK_PLANKS: 30
  SPRUCE_PLANKS: 30
  BIRCH_PLANKS: 30
  JUNGLE_PLANKS: 30
  ACACIA_PLANKS: 30
  DARK_OAK_PLANKS: 30
  MANGROVE_PLANKS: 30
  CHERRY_PLANKS: 30

  COBBLESTONE: 60
  STONE_BRICKS: 80
  BRICKS: 70

  OAK_FENCE: 20
  OAK_DOOR: 18

# ======================
# BUILDER
# ======================
builder:
  repair_amount: 8
  repair_distance: 5
  reward_money: 2
  reward_xp: 1

# ======================
# REGEN MINING
# ======================
regen_mining:
  enabled: true
  restore_seconds: 90
  only_outside_base: true

# ======================
# MINER PROGRESS
# ======================
miner_progress:
  enabled: true
  exp_per_block: 2
  level_xp_base: 80
  level_xp_add_per_level: 40
  max_level: 10
  haste_max_level: 4
